#!/bin/sh
if [ -r /proc/cpuinfo ]; then
    # this should only exist on virtual guest machines,
    # tested on vmware, xen, kvm
    if grep -q "hypervisor" /proc/cpuinfo; then
        # this file is aviable in xen guest systems
        if [ -r /sys/hypervisor/type ]; then
            if grep -q -i "xen" /sys/hypervisor/type; then
                echo virtual_by_xen
                exit 
            fi
        else
            if [ -r /sys/class/dmi/id/product_name ]; then
                if grep -q -i 'vmware' /sys/class/dmi/id/product_name; then
                    echo "virtual_by_vmware"
                    exit
                elif grep -q -i 'bochs' /sys/class/dmi/id/product_name; then
                    echo "virtual_by_kvm"
                    exit 
                elif grep -q -i 'virtualbox' /sys/class/dmi/id/product_name; then
                    echo "virtual_by_virtualbox"
                    exit 
                fi
            fi
        fi
        echo "virtual_by_unknown"
    else
        echo "physical"
    fi
else
    echo "unknown"
fi
