#!/bin/sh

SRC_PATH="/usr/local/src"
AUR_URL="https://aur.archlinux.org"

if [ -f "$__object/parameter/name" ]; then
    name="$__object/parameter/name"
else
    name="$__object_id"
fi

# Clone AUR package
git_folder="$SRC_PATH/$name"
git_source="$AUR_URL/$name.git"
__git $git_folder --source $git_source
